id: I4BD9F852
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-11T13:33:05.215805'
last_modified: '2022-06-11T13:33:05.215812'
parser: null
source_metadata:
  title: Buddhagupta
  language: bo
  description: Instructions
  volume:
    f2BEC:
      title: An Extensive Commentary on the Four Immeasurables
      base_file: f2BEC.txt
      order: 1
      parent: Instructions
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
